//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Cpu { get; set; }
        public string HardDrive { get; set; }
        public string GraphicCard { get; set; }
        public string Ram { get; set; }
        public decimal Price { get; set; }
    }
}
